default_target = "jetson-agx-orin-devkit"
supported_targets = ["jetson-agx-orin-devkit"]

[ext.avocado-bsp-jetson-agx-orin-devkit]
version = "1.0.0"
release = "r0"
vendor = "Avocado Linux <info@avocadolinux.org>"
summary = "Board support for the Nvidia Jetson AGX Orin devkit"
description = "Board support for the Nvidia Jetson AGX Orin devkit"
license = "Apache-2.0"
url = "https://github.com/avocadolinux/avocado-os"
types = ["sysext", "confext"]
on_merge = [
  "udevadm control --reload",
  "udevadm trigger --type=subsystems --action=add --settle",
  "udevadm trigger --type=devices --action=add --settle"
]

[ext.avocado-bsp-jetson-agx-orin-devkit.dependencies]
kernel-module-snd-soc-tegra186-asrc = "*"
kernel-module-snd-soc-tegra210-admaif = "*"
kernel-module-snd-soc-tegra-utils = "*"
kernel-module-snd-soc-tegra210-ope = "*"
kernel-module-snd-soc-tegra210-mixer = "*"
kernel-module-snd-soc-tegra-pcm = "*"
kernel-module-snd-soc-tegra186-arad = "*"
kernel-module-snd-soc-tegra210-mvc = "*"
kernel-module-snd-soc-tegra186-dspk = "*"
kernel-module-snd-soc-tegra210-dmic = "*"
kernel-module-snd-soc-tegra210-adx = "*"
kernel-module-snd-soc-tegra210-amx = "*"
kernel-module-snd-soc-tegra210-sfc = "*"
kernel-module-snd-soc-tegra210-i2s = "*"
kernel-module-snd-soc-tegra210-ahub = "*"
kernel-module-tegra210-adma = "*"
kernel-module-snd-soc-tegra-audio-graph-card = "*"
kernel-module-snd-hda-codec-hdmi = "*"
kernel-module-crct10dif-ce = "*"
kernel-module-snd-soc-audio-graph-card = "*"
kernel-module-snd-soc-simple-card-utils = "*"
kernel-module-tegra-aconnect = "*"
kernel-module-governor-userspace = "*"
kernel-module-snd-hda-tegra = "*"
kernel-module-spidev = "*"
kernel-module-snd-hda-codec = "*"
kernel-module-snd-hda-core = "*"
kernel-module-at24 = "*"
kernel-module-tegra-drm = "*"
kernel-module-tegra-wmark = "*"
kernel-module-cec = "*"
kernel-module-drm-kms-helper = "*"
kernel-module-drm = "*"
kernel-module-nfnetlink = "*"
kernel-module-r8168 = "*"
kernel-module-nvvrs-pseq-rtc = "*"
kernel-module-fusb301 = "*"
kernel-module-tegra234-oc-event = "*"
kernel-module-nvpmodel-clk-cap = "*"
kernel-module-thermal-trip-event = "*"
kernel-module-tegra-cactmon-mc-all = "*"
kernel-module-tegra234-aon = "*"
kernel-module-mc-hwpm = "*"
kernel-module-pwm-tegra-tachometer = "*"
kernel-module-spi-tegra114 = "*"
kernel-module-pwm-tegra = "*"
kernel-module-nvhwpm = "*"
kernel-module-tegra-bpmp-thermal = "*"
kernel-module-nvidia-vrs-pseq = "*"
kernel-module-host1x-fence = "*"
kernel-module-pwm-fan = "*"
kernel-module-nvgpu = "*"
kernel-module-governor-pod-scaling = "*"
kernel-module-mc-utils = "*"
kernel-module-nvmap = "*"
kernel-module-nvsciipc = "*"
kernel-module-host1x = "*"
kernel-module-ina3221 = "*"
kernel-module-tegra-xudc = "*"
kernel-module-phy-tegra194-p2u = "*"
kernel-module-pcie-tegra194 = "*"
kernel-module-nvme = "*"
kernel-module-nvme-core = "*"
kernel-module-ipv6 = "*"
linux-firmware-rtl8168 = "*"

[sdk]
image = "avocadolinux/sdk:apollo-edge"
