default_target = "reterminal-dm"
supported_targets = ["reterminal-dm"]
src_dir = "../../"

[ext.avocado-bsp-reterminal-dm]
version = "1.0.0"
release = "r0"
vendor = "Avocado Linux <info@avocadolinux.org>"
summary = "Board support for the ReTerminal DM"
description = "Board support for the ReTerminal DM"
license = "Apache-2.0"
url = "https://github.com/avocadolinux/avocado-os"
overlay = "bsp/reterminal-dm/overlay"
types = ["sysext", "confext"]
modprobe = ["gpio-pca953x", "rtc-pcf8563w"]
on_merge = [
  "udevadm control --reload",
  "udevadm trigger --type=subsystems --action=add --settle",
  "udevadm trigger --type=devices --action=add --settle"
]

[ext.avocado-bsp-reterminal-dm.dependencies]
kernel-module-nfnetlink = "*"
kernel-module-cdc-acm = "*"
kernel-module-joydev = "*"
kernel-module-imx219 = "*"
kernel-module-mcp251xfd = "*"
kernel-module-goodix-ts = "*"
kernel-module-v4l2-cci = "*"
kernel-module-spidev = "*"
kernel-module-can-dev = "*"
kernel-module-brcmfmac = "*"
kernel-module-brcmutil = "*"
kernel-module-hci-uart = "*"
kernel-module-btbcm = "*"
kernel-module-snd-soc-simple-card = "*"
kernel-module-v3d = "*"
kernel-module-snd-soc-simple-card-utils = "*"
kernel-module-bluetooth = "*"
kernel-module-ecdh-generic = "*"
kernel-module-gpu-sched = "*"
kernel-module-drm-shmem-helper = "*"
kernel-module-cfg80211 = "*"
kernel-module-raspberrypi-hwmon = "*"
kernel-module-ecc = "*"
kernel-module-i2c-mux-pinctrl = "*"
kernel-module-gpio-pca953x = "*"
kernel-module-i2c-mux = "*"
kernel-module-snd-soc-tlv320aic3x-i2c = "*"
kernel-module-bcm2835-unicam-legacy = "*"
kernel-module-snd-soc-tlv320aic3x = "*"
kernel-module-rfkill = "*"
kernel-module-libaes = "*"
kernel-module-v4l2-dv-timings = "*"
kernel-module-bcm2835-v4l2 = "*"
kernel-module-bcm2835-codec = "*"
kernel-module-bcm2835-isp = "*"
kernel-module-v4l2-fwnode = "*"
kernel-module-v4l2-async = "*"
kernel-module-dwc2 = "*"
kernel-module-bcm2835-mmal-vchiq = "*"
kernel-module-rpi-hevc-dec = "*"
kernel-module-at24 = "*"
kernel-module-vc-sm-cma = "*"
kernel-module-v4l2-mem2mem = "*"
kernel-module-pwm-bcm2835 = "*"
kernel-module-videobuf2-vmalloc = "*"
kernel-module-videobuf2-dma-contig = "*"
kernel-module-videobuf2-memops = "*"
kernel-module-videobuf2-v4l2 = "*"
kernel-module-snd-soc-bcm2835-i2s = "*"
kernel-module-videodev = "*"
kernel-module-spi-bcm2835 = "*"
kernel-module-snd-bcm2835 = "*"
kernel-module-videobuf2-common = "*"
kernel-module-raspberrypi-gpiomem = "*"
kernel-module-mc = "*"
kernel-module-pwm-bl = "*"
kernel-module-uio-pdrv-genirq = "*"
kernel-module-uio = "*"
kernel-module-rtc-pcf8563w = "*"
kernel-module-ili9881d = "*"
kernel-module-backlight = "*"
kernel-module-i2c-dev = "*"
kernel-module-sch-fq-codel = "*"
kernel-module-ipv6 = "*"
kernel-module-r8169 = "*"
kernel-module-realtek = "*"
kernel-module-ltr30x = "*"

fwup = "*"

[sdk]
image = "avocadolinux/sdk:apollo-edge"
