default_target = "jetson-orin-nano-devkit"
supported_targets = ["jetson-orin-nano-devkit"]

[ext.avocado-bsp-jetson-orin-nano-devkit]
version = "1.0.0"
release = "r0"
vendor = "Avocado Linux <info@avocadolinux.org>"
summary = "Board support for the Nvidia Jetson Orin Nano devkit"
description = "Board support for the Nvidia Jetson Orin Nano devkit"
license = "Apache-2.0"
url = "https://github.com/avocadolinux/avocado-os"
types = ["sysext", "confext"]
on_merge = [
  "udevadm control --reload",
  "udevadm trigger --type=subsystems --action=add --settle",
  "udevadm trigger --type=devices --action=add --settle"
]

[ext.avocado-bsp-jetson-orin-nano-devkit.dependencies]
kernel-module-snd-soc-tegra186-asrc = "*"
kernel-module-snd-soc-tegra210-admaif = "*"
kernel-module-snd-soc-tegra-utils = "*"
kernel-module-snd-soc-tegra210-ope = "*"
kernel-module-snd-soc-tegra210-mixer = "*"
kernel-module-snd-soc-tegra-pcm = "*"
kernel-module-snd-soc-tegra186-arad = "*"
kernel-module-snd-soc-tegra210-mvc = "*"
kernel-module-snd-soc-tegra186-dspk = "*"
kernel-module-snd-soc-tegra210-dmic = "*"
kernel-module-snd-soc-tegra210-adx = "*"
kernel-module-snd-soc-tegra210-amx = "*"
kernel-module-snd-soc-tegra210-sfc = "*"
kernel-module-snd-soc-tegra210-i2s = "*"
kernel-module-snd-soc-tegra210-ahub = "*"
kernel-module-tegra210-adma = "*"
kernel-module-snd-soc-tegra-audio-graph-card = "*"
kernel-module-snd-hda-codec-hdmi = "*"
kernel-module-crct10dif-ce = "*"
kernel-module-snd-soc-audio-graph-card = "*"
kernel-module-snd-soc-simple-card-utils = "*"
kernel-module-tegra-aconnect = "*"
kernel-module-governor-userspace = "*"
kernel-module-snd-hda-tegra = "*"
kernel-module-spidev = "*"
kernel-module-snd-hda-codec = "*"
kernel-module-snd-hda-core = "*"
kernel-module-at24 = "*"
kernel-module-tegra-drm = "*"
kernel-module-tegra-wmark = "*"
kernel-module-cec = "*"

kernel-module-nvvrs-pseq-rtc = "*"
kernel-module-fusb301 = "*"
kernel-module-tegra234-oc-event = "*"
kernel-module-nvpmodel-clk-cap = "*"
kernel-module-thermal-trip-event = "*"
kernel-module-tegra-cactmon-mc-all = "*"
kernel-module-tegra234-aon = "*"
kernel-module-mc-hwpm = "*"
kernel-module-pwm-tegra-tachometer = "*"
kernel-module-spi-tegra114 = "*"
kernel-module-pwm-tegra = "*"
kernel-module-nvhwpm = "*"
kernel-module-tegra-bpmp-thermal = "*"
kernel-module-nvidia-vrs-pseq = "*"
kernel-module-host1x-fence = "*"
kernel-module-pwm-fan = "*"
kernel-module-nvgpu = "*"
kernel-module-governor-pod-scaling = "*"
kernel-module-mc-utils = "*"
kernel-module-nvmap = "*"
kernel-module-nvsciipc = "*"
kernel-module-host1x = "*"
kernel-module-ina3221 = "*"
kernel-module-tegra-xudc = "*"
kernel-module-phy-tegra194-p2u = "*"
kernel-module-pcie-tegra194 = "*"
kernel-module-nvme = "*"
kernel-module-nvme-core = "*"
linux-firmware-rtl8168 = "*"

# Networking/iptables modules
kernel-module-xt-conntrack = "*"
kernel-module-xt-masquerade = "*"
kernel-module-nf-conntrack-netlink = "*"
kernel-module-iptable-nat = "*"
kernel-module-nf-nat = "*"
kernel-module-xt-addrtype = "*"
kernel-module-iptable-filter = "*"
kernel-module-ip-tables = "*"
kernel-module-x-tables = "*"
kernel-module-bnep = "*"
kernel-module-sch-fq-codel = "*"

# WiFi/Bluetooth modules (Realtek RTW88)
kernel-module-rtw88-8822ce = "*"
kernel-module-rtw88-8822c = "*"
kernel-module-rtw88-pci = "*"
kernel-module-rtw88-core = "*"
kernel-module-mac80211 = "*"
kernel-module-rtk-btusb = "*"
kernel-module-libarc4 = "*"
kernel-module-cfg80211 = "*"

# Ethernet modules
kernel-module-r8169 = "*"
kernel-module-realtek = "*"

# CAN bus modules
kernel-module-mttcan = "*"
kernel-module-nvpps = "*"
kernel-module-can-dev = "*"

# Camera/video modules
kernel-module-nvhost-nvcsi-t194 = "*"
kernel-module-nvhost-vi5 = "*"
kernel-module-nvhost-isp5 = "*"
kernel-module-snd-soc-tegra-machine-driver = "*"
kernel-module-tegra-camera = "*"
kernel-module-v4l2-dv-timings = "*"
kernel-module-v4l2-fwnode = "*"
kernel-module-v4l2-async = "*"
kernel-module-videobuf2-dma-contig = "*"
kernel-module-videobuf2-memops = "*"
kernel-module-nvhost-nvcsi = "*"
kernel-module-tegra-camera-platform = "*"
kernel-module-capture-ivc = "*"
kernel-module-tegra-camera-rtcpu = "*"
kernel-module-ivc-bus = "*"
kernel-module-hsp-mailbox-client = "*"
kernel-module-ivc-ext = "*"
kernel-module-videobuf2-v4l2 = "*"
kernel-module-videodev = "*"
kernel-module-videobuf2-common = "*"
kernel-module-mc = "*"
kernel-module-nvhost-capture = "*"

# Display modules
kernel-module-drm-dp-aux-bus = "*"
kernel-module-drm-display-helper = "*"

# NVIDIA proprietary modules
kernel-module-nvidia-drm = "*"
kernel-module-nvidia-modeset = "*"
kernel-module-nvidia = "*"
kernel-module-tegra-dce = "*"
kernel-module-tsecriscv = "*"
kernel-module-host1x-nvhost = "*"

# Misc modules
kernel-module-fuse = "*"

[sdk]
image = "avocadolinux/sdk:apollo-edge"
