supported_targets = ["raspberrypi4", "raspberrypi5", "reterminal", "reterminal-dm"]
src_dir = "../../"

[ext.avocado-ext-webkit]
version = "1.0.0"
release = "r0"
vendor = "Avocado Linux <info@avocadolinux.org>"
summary = "WPE WebKit browser and display utilities"
description = "WPE WebKit browser and display utilities"
license = "Apache-2.0"
url = "https://github.com/avocadolinux/avocado-os"
types = ["sysext", "confext"]
enable_services = ["cog.service"]
on_merge = ["systemctl restart --no-block cog.service"]

[ext.avocado-ext-webkit.reterminal-dm]
overlay = "extensions/webkit/overlays/reterminal-dm"

[ext.avocado-ext-webkit.reterminal]
overlay = "extensions/webkit/overlays/reterminal"

[ext.avocado-ext-webkit.dependencies]
cog = "*"
wpewebkit = "*"
weston = "*"
wpebackend-fdo = "*"
ca-certificates = "*"
p11-kit = "*"
ethtool = "*"

[sdk]
image = "avocadolinux/sdk:apollo-edge"

[sdk.dependencies]
avocado-sdk-toolchain = "*"
