supported_targets = ["raspberrypi4", "raspberrypi5", "reterminal", "reterminal-dm"]
# Working on adding full support for all targets
# supported_targets = "*"

src_dir = "../../"

[ext.avocado-ext-podman]
version = "1.0.0"
release = "r0"
vendor = "Avocado Linux <info@avocadolinux.org>"
summary = "Avocado Podman container engine"
description = "Avocado Podman container engine"
license = "Apache-2.0"
url = "https://github.com/avocadolinux/avocado-os"
types = ["sysext", "confext"]

[ext.avocado-ext-podman.dependencies]
podman = "*"
kernel-module-br-netfilter = "*"
kernel-module-bridge = "*"

[sdk]
image = "avocadolinux/sdk:apollo-edge"

[sdk.dependencies]
avocado-sdk-toolchain = "*"
