supported_targets = "*"

[ext.avocado-ext-sshd]
version = "1.0.0"
release = "r0"
vendor = "Avocado Linux <info@avocadolinux.org>"
summary = "OpenSSH server"
description = "OpenSSH server"
license = "Apache-2.0"
url = "https://github.com/avocadolinux/avocado-os"

types = ["sysext", "confext"]
enable_services = ["sshd.socket"]
on_merge = ["systemctl restart sshd.socket"]

[ext.avocado-ext-sshd.dependencies]
openssh = "*"

[ext.avocado-ext-sshd.sdk.dependencies]
nativesdk-openssh-ssh = "*"

[sdk]
image = "avocadolinux/sdk:apollo-edge"

[sdk.dependencies]
avocado-sdk-toolchain = "*"
