supported_targets = "*"
src_dir = "../../"

[ext.avocado-ext-dev]
version = "1.0.0"
release = "r0"
vendor = "Avocado Linux <info@avocadolinux.org>"
summary = "Avocado development tools"
description = "Avocado development tools"
license = "Apache-2.0"
url = "https://github.com/avocadolinux/avocado-os"
types = ["sysext", "confext"]
on_merge = ["btrfs filesystem resize max /var"]

[ext.avocado-ext-dev.dependencies]
avocado-hitl = "*"
avocado-ext-sshd-dev = { ext = "avocado-ext-sshd-dev", config = "extensions/sshd-dev/avocado.toml" }
rsync = "*"

[ext.avocado-ext-dev.sdk.dependencies]
nativesdk-avocado-hitl = "*"
nativesdk-openssh-ssh = "*"
nativesdk-openssh-scp = "*"
nativesdk-rsync = "*"

[sdk]
image = "avocadolinux/sdk:apollo-edge"

[sdk.dependencies]
avocado-sdk-toolchain = "*"
